### PR TITLE
New PR for Aaron Sugg's story

### PR DESCRIPTION
**Pull request by lethain**
This replaces https://github.com/lethain/staff-eng/pull/41

### CODE REVIEW

**Comment by lethain** [comment]
FYI, screen cap

Screen Shot 2021-01-17 at 2 48 14 PM

**Comment by ktheory** [comment]
Thank you, this looks great.

**Comment by lethain** [comment]
@lethain add missing comma after website link

**Comment by lethain** [comment]
Hi @ktheory! Quick updates:

1. It's merged!
2. It's deployed: https://staffeng.com/stories/aaron-suggs
3. Email will go out at 9AM PT sharing your story
4. I didn't fully click that you'd written this piece in Increment ( https://increment.com/documentation/what-a-deploy-bot-taught-glossier-about-documentation/ ), but loved it

Thanks again for contributing your story!

**Pull request merged**
