### PR TITLE
Adding a new story for adambender

### PR DESCRIPTION
**Pull request by adambender**
Hey all, I really appreciate this project! I wish it had existed when I first hit Staff myself.

Hope my PR meets the bar for inclusion, feel free to let me know if anything needs to change.

### CODE REVIEW

**Review by lethain — APPROVED** [review]

**Comment by lethain** [comment]
Quick update -- I realize I have not done a StaffEng deploy since switching computers and it's going to take me more than 3 minutes before my next meeting, so I will have to get this deployed this evening!

**Comment by adambender** [comment]
Thank you for taking a look!

Those of us at very large companies find it is often easier to look inward than connect outward - only so many things a human mind can connect with after all  - so I'm glad this resonated with you.

No worries on the deployment timing, it took me a couple months to find all the time needed to write it, I can wait a few more hours to see it live :) 

Thanks again for creating this collection and the opportunity for engineers to share their experience.

**Comment by lethain** [comment]
It's up at https://staffeng.com/stories/adam-bender

Thanks again for sharing! Email will go out at either 8AM or 9AM PT tomorrow for the mailing list, and will do some tweets and post on LI sometime tomorrow as well!

**Comment by adambender** [comment]
Hey Will I just realized there is a small correction needed in the first sentence of my first answer... I was recently promoted to Principal Engineer and I forgot to adjust the mention. I believe I covered it everywhere else. LMK if you want me to make another PR or if you can address... Sorry about that!

**Comment by lethain** [comment]
Updated:
https://github.com/lethain/staff-eng/commit/8f8fa7742db7847912c61f9d18153d4ba81b4911

**Pull request merged**
