### PR TITLE
Add Aaron Suggs' story

### PR DESCRIPTION
**Pull request by ktheory**
I've learned a lot reading other StaffEng stories this past year. Thank you! 

It would be an honor to share my story.

### CODE REVIEW

**Comment by lethain** [comment]
@ktheory -- thank you for sharing your story! I'll take a look tomorrow and either merge it in or potentially suggest a couple of edits

**Comment by ktheory** [comment]
Re-reading, I see several missing/extra words. I'll take a pass to correct those and be more concise ASAP.

**Comment by lethain** [comment]
Thanks @ktheory! No rush, will wait until you give the OK

**Comment by ktheory** [comment]
@lethain okay, it's ready for your review. Cheers!

**Comment by lethain** [comment]
Hi @ktheory! This is an awesome story. I pulled it into the `ktheory` branch on the repo, and opened up a new PR with it, https://github.com/lethain/staff-eng/pull/45 , so that I could make some very minor grammatical changes.

I am going to close this PR and move work to #45, but looks awesome to me, and my plan will be to merge it on Thursday afternoon (1/20) to go out on the email list around 9AM PT on Friday, 1/21.

Let me know if there's anything else I can modify/do to help before it goes!

Screen Shot 2021-01-17 at 2 48 14 PM

**Pull request closed without merging**
