### PR TITLE
docs: Add Mikhail Chernykh's story

### PR DESCRIPTION
**Pull request by netme**
Hi @lethain, thanks for driving the StaffEng.com website, I particularly like the stories part. 

I would like to share my a story of being a Staff Engineer at Indeed. Hope it will give some visibility to our organization. 

Looking forward to hearing from you!

### CODE REVIEW

**Comment by lethain** [comment]
@netme thank you for submitting this! I'll read it over in the next day or two and comment with suggestions (or merge if I don't have any)! Will work to get this out before next week.

**Comment by netme** [comment]
Thanks a lot @lethain, looking forward to hearing from you!

**Comment by lethain** [comment]
@netme great read. merging in and will deploy in a bit

**Comment by netme** [comment]
Thanks a lot @lethain , looking forward to see it live!

**Comment by lethain** [comment]
@netme -- https://staffeng.com/stories/mikhail-chernykh (potentially cached on some CDNs for another 1-2 minutes, but love for me! )

**Comment by lethain** [comment]
Will go out in newsletter either in 30 minutes or 1 week and 30 minutes. I think next week :-)

**Comment by netme** [comment]
Thanks Will, it works! And no rush

**Pull request merged**
